server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://rising-test.cnqjm0ka59ku.ap-northeast-2.rds.amazonaws.com/RisingTest?autoReconnect=true # 변경해주세요
    username: admin # 변경해주세요
    password: DBcodus1206^^ # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전